import textwrap
from pathlib import Path
from typing import Literal

def generate_dockerfile(script_path: str, port: int = 8000) -> str:
    """
    Generates a production-ready Dockerfile for an Eidos application.
    """
    return textwrap.dedent(f"""
        # Generated by Eidos Deploy
        FROM python:3.12-slim
        
        WORKDIR /app
        
        # Install system dependencies
        RUN apt-get update && apt-get install -y --no-install-recommends \\
            build-essential \\
            git \\
            && rm -rf /var/lib/apt/lists/*
            
        # Install Eidos Framework
        # In a real scenario, this would point to PyPI or a private feed
        RUN pip install eidos-framework[all]
        
        # Copy source code
        COPY . /app
        
        # Set PYTHONPATH
        ENV PYTHONPATH=/app/src
        ENV EIDOS_LOG_LEVEL=INFO
        
        # Expose port (for REST/Studio)
        EXPOSE {port}
        
        # Default Entrypoint
        # Users can override this in docker-compose
        CMD ["eidos", "run", "{script_path}"]
    """).strip()

def generate_compose(project_name: str, script_path: str, port: int = 8000) -> str:
    """
    Generates a docker-compose.yml for the stack.
    """
    return textwrap.dedent(f"""
        version: '3.8'
        
        services:
          {project_name}:
            build: .
            container_name: {project_name}
            environment:
              - EIDOS_LOG_LEVEL=INFO
              - EIDOS_DEFAULT_BACKEND=polars
            ports:
              - "{port}:{port}"
            volumes:
              - ./src:/app/src
              - ./data:/app/data
            command: eidos run {script_path}
            deploy:
              resources:
                limits:
                  cpus: '2.0'
                  memory: 2G
    """).strip()
